In [ ]:
# code snippets that may be useful

# !pip install xlrd
# df = pd.read_excel('sample.xlsx', sheet_name='sheet2')

# stats.norm.cdf(zscore)
# stats.t.cdf(tscore, df=df)

# stats.norm.ppf(probability)
# stats.t.ppf(probability, df=df)

# chi_square_stat, p_value = stats.chisquare(observed_values, f_exp=expected_values)

# chi_sq_Stat, p_value, deg_freedom, exp_freq = stats.chi2_contingency(quality_array, correction=False)


# f_test, p_val = stats.f_oneway(sectionA, sectionB, sectionC)

#mod = ols('marks ~ section', data = marks_df).fit()
#aov_table = sm.stats.anova_lm(mod, typ=2)
#print(aov_table)

In [1]:
# import libraries
import numpy as np
import pandas as pd
from scipy import stats

# ANOVA
import statsmodels.api         as     sm
from   statsmodels.formula.api import ols

[Q1] A cable internet service provider ran two campaigns. In one they offered one month free if the subscriber paid for 6 months. In another they offered two months free if the subscriber paid for 12 months. Data relating to both campaigns are in the data workbook sheets q1 and q11.
Using formal methods, test if they were both equally effective in winning customers.

here we will go **chi_sqaure test for inpendence** to check if grade are dependent on mode of education

#Null hypo -        
h0: Response to Campaigns 1 and 2 is equal in obs and expected

#Alternamte hypo -  
h1:Response to Campaigns 1 and 2 not equal in obs and expected

using right tail chi_sqr test for conformation

In [45]:
data1=pd.read_excel("midterm_data.xlsx")
data1.head()

agent_id region                               pitch         result
0      1429      N  pay for 6 months, get 1 month free              N
1      1047      N  pay for 6 months, get 1 month free              N
2      1356      W  pay for 6 months, get 1 month free  AcceptedOffer
3      1230      W  pay for 6 months, get 1 month free              N
4      1818      E  pay for 6 months, get 1 month free              N

In [46]:
data2 = pd.read_excel('midterm_data.xlsx', sheet_name = 'q11')                 
data2.head()

agent_id region                                 pitch result
0      1013      S  pay for 12 months, get 2 months free      N
1      1042      E  pay for 12 months, get 2 months free      N
2      1044      E  pay for 12 months, get 2 months free      N
3      1052      N  pay for 12 months, get 2 months free      N
4      1074      N  pay for 12 months, get 2 months free      N

In [47]:
p=pd.concat([data1,data2],axis=0)
len(p)

117

In [48]:
pd.crosstab(p.pitch,p.result)

result                                AcceptedOffer   N
pitch                                                  
pay for 12 months, get 2 months free             12  44
pay for 6 months, get 1 month free               19  42

In [49]:
chi_array1 = ([[12,44],[19,42]])
chi_array1

[[12, 44], [19, 42]]

In [50]:
obs1 = [12,44]
obs2 = [19,42]
exp1 = [31*(56/117), 86*(56/117)]
exp2 = [31*(61/117), 86*(61/117)]

In [53]:
exp1, exp2

([14.837606837606838, 41.162393162393165],
 [16.162393162393162, 44.83760683760684])

In [51]:
exp_val=np.append(exp1,exp2)
obs_val=np.append(obs1,obs2)

In [55]:
sum3=0
for i in range(len(obs_val)):
    a2=((obs_val[i]-exp_val[i])**2/exp_val[i])
    sum3+=a2
chi2_stat3=sum3
chi2_stat3

1.4160677171634832

In [68]:
#Calculating the Chi square statistic 
import numpy as np 
o1 = np.array([19,42])
o2 = np.array([12,44])
e1 = np.array([16.16,44.84])
e2 = np.array([14.84,41.16])
a = (o1-e1)**2/e1
b = (o2-e2)**2/e2
chi2_stat3 = np.sum(a)+np.sum(b) #This is the chi square statistic we got 
chi2_stat3

1.4184453055642299

In [61]:
chi2_cri = stats.chi2.isf(0.05, df=1) #(2-1)(2-1)
chi2_cri 

3.8414588206941285

In [67]:
aalpha = 0.05
p_val1 = stats.chi2.sf(1.418, 1)
p_val

0.30411193171110124

In [66]:
# python library
chi_sq_Stat, p_value, deg_freedom, exp_freq = stats.chi2_contingency(chi_array1, correction=False)

print('Chi-square statistic %3.5f P value %1.6f Degrees of freedom %d' %(chi_sq_Stat, p_value,deg_freedom))

Chi-square statistic 1.41607 P value 0.234052 Degrees of freedom 1


In [ ]:
**Decision**

As chi_square_stat < chi_c in right tail test, the sample falls in acceptance zone. Hence we cannot reject null hypothesis

Also as p_value < alpha in right tail test, the sample falls in acceptance zone. Hence we cannot reject null hypothesis

both campigine equally effective in winning customers.

[Q2] The agents of the cable internet company are required to make phone calls to customers and offer them deals and win subscriptions. A metric in this process is the number of calls made per day. Initially the agents were paid fixed salary without any incentives for winning new customers. The management recently changed this and offered incentives to the agents hoping they will make more calls per day. This information is available in sheet q2. The columns are Calls_Salary and Calls_Incentive for each agent.

You are required to test if the change in payment to include incentives for winning customers has increased the number of calls made per day.

In [69]:
data3 = pd.read_excel('midterm_data.xlsx', sheet_name = 'q2')                 
data3.head()

agent_id  Calls_Salary  Calls_Incentive
0      1429             8               11
1      1047             7               10
2      1356             9               12
3      1230            10                7
4      1818             7               14

In [ ]:
#Let mu_1 be the average number of calls per day initially.
#mu_2 be the average calls per day after incentives

# H0 : mu_1 - mu_2 >= 0
# H1 : mu_1 - mu_2 < 0   # incentives for winning customers has increased the average number of calls

In [85]:
data3.shape

(59, 3)

In [87]:
x1 = np.array(data3["Calls_Salary"])  #Calls before incentives
x2 = np.array(data3["Calls_Incentive"])   #Calls after incentives  
D = x1 - x2
D

array([-3, -3, -3,  3, -7, -1, -7, -4,  1, -3, -3, -5, -4, -4, -3, -4, -3,
       -7, -5, -6, -7, -4,  0,  0, -4, -4, -2, -6, -6, -5,  1, -6,  2, -6,
       -1, -3, -4, -2, -5, -2, -5, -7,  2, -5, -3, -7, -1, -6, -6, -4, -7,
       -6, -3, -3,  0, -3, -6, -8,  2], dtype=int64)

In [88]:
n = len(D)

In [89]:
D_bar = np.mean(D)
S_D = np.std(D,ddof=1)

In [90]:
t_crit = stats.t.ppf(0.05,df=n-1)  #left tailed test
t_crit

-1.6715527621536728

In [91]:
t = (D_bar - 0)/(S_D/np.sqrt(n))
t

-10.252069705503347

In [92]:
pval = stats.t.cdf(t,df=n-1)
pval

6.119313351322935e-15

**Decision**

* As t < tc in left tail test, the samples lie in rejection zone. Hence we reject the null hypothesis.
* as p_value < alpha in left tail test, the samples lie in rejection zone. Hence we reject the null hypothesis.
* Hence the impact of incentives is statistically significant for winning customers and has increased the average number of calls

[Q3] University requires grades to be distributed according to their norms:
A (5%), B(30%), C(50%), D(10%), F(5%) 
For a recent exam, the grades were as given in sheet q3.

Test if this follows the norms.

here we will go **chi_sqaure goodness of fit test** to check if our observed values fits the expected probablity distribution

#Null hypo -        
h0: Observed grade distribution is similar to Expected grade distribution.

#Alternamte hypo -  
h1:Observed grade distribution is not similar to Expected grade distribution.

using right tail chi_sqr test for conformation

In [5]:
data4 = pd.read_excel('midterm_data.xlsx', sheet_name = 'q3')                 
data4.head()

rollnumber       mode grade
0           1  Classroom     D
1           2  Classroom     F
2           3  Classroom     C
3           4  Classroom     C
4           5  Classroom     A

In [9]:
n = len(data4)
n

35

In [7]:
s1 = data4[["rollnumber","grade"]].groupby(["grade"]).count()
s1

rollnumber
grade            
A               6
B               5
C               9
D               8
F               7

In [10]:
obs_grade = [6,5,9,8,7]
exp_grade = [0.05*n, 0.30*n, 0.50*n, 0.10*n, 0.05*n]

In [15]:
chi_c = stats.chi2.isf(0.05, df = 5-1)
chi_c

9.487729036781158

In [16]:
sum1=0
for i in range(len(obs_grade)):
    a1=((obs_grade[i]-exp_grade[i])**2/exp_grade[i])   # formula
    sum1+=a1
chi2_stat1=sum1

In [17]:
chi2_stat1

38.86666666666667

In [21]:
p_val = stats.chi2.sf(38.866666, df = 5-1)
p_val

7.422495206977314e-08

In [11]:
#python libabry
chi_square_stat, p_value = stats.chisquare(obs_grade, f_exp=exp_grade)

In [12]:
chi_square_stat

38.86666666666667

In [13]:
p_value

7.422492853897377e-08

**Decision**

As chi_square_stat > chi_c in right tail test, the sample lie in rejection zone. Hence we reject null hypothesis

Also as p_value < alpha in right tail test, the sample lie in rejection zone. Hence we reject null hypothesis

This sample fails to meet the norms

[Q4] There are keen discussions about online vs classroom in various segments of the society. Using the data in sheet q3, test if performance of students is impacted by the mode of engagement.

here we will go **chi_sqaure test for inpendence** to check if grade are dependent on mode of education

#Null hypo -        
h0: grades are independent of mode of eduaction

#Alternamte hypo -  
h1:rades are not independent of mode of education

using right tail chi_sqr test for conformation

In [17]:

data4 = pd.read_excel('midterm_data.xlsx', sheet_name = 'q3')                 
data4.head()

rollnumber       mode grade
0           1  Classroom     D
1           2  Classroom     F
2           3  Classroom     C
3           4  Classroom     C
4           5  Classroom     A

In [23]:
s2 = data4[["rollnumber","grade", "mode"]].groupby(["grade", "mode"]).count()
s2

rollnumber
grade mode                 
A     Classroom           6
B     Classroom           3
      Online              2
C     Classroom           5
      Online              4
D     Classroom           5
      Online              3
F     Classroom           6
      Online              1

In [26]:
len(data4)

35

In [41]:
chi_array = np.array([[6,0],[3,2],[5,4],[5,3],[6,1]])
chi_array


array([[6, 0],
       [3, 2],
       [5, 4],
       [5, 3],
       [6, 1]])

In [24]:
obs_classroom = [6,3,5,5,6]
obs_online = [0,2,4,3,1]

In [27]:
exp_classroom = [25*(6/35), 25*(5/35), 25*(9/35), 25*(8/35), 25*(7/35)]
exp_online = [10*(6/35), 10*(5/35), 10*(9/35), 10*(8/35), 10*(7/35)]

In [28]:
exp_classroom

[4.285714285714286,
 3.571428571428571,
 6.428571428571428,
 5.714285714285714,
 5.0]

In [29]:
exp_online

[1.7142857142857144,
 1.4285714285714284,
 2.571428571428571,
 2.2857142857142856,
 2.0]

In [32]:
exp_val=np.append(exp_classroom,exp_online)
obs_val=np.append(obs_classroom,obs_online)

In [33]:
sum2=0
for i in range(len(obs_val)):
    a2=((obs_val[i]-exp_val[i])**2/exp_val[i])
    sum2+=a2
chi2_stat2=sum2

In [34]:
chi2_stat2

4.8436111111111115

In [37]:
chi2_c = stats.chi2.isf(0.05, df=1*4)
chi2_c

9.487729036781158

In [39]:
p_val = stats.chi2.sf(4.84, df= 4)
p_val

0.30411193171110124

In [30]:

obs_a = np.array([6,0])
obs_b = np.array([3,2])
obs_c = np.array([5,4])
obs_d = np.array([5,3])
obs_f = np.array([6,1])
exp_a = np.array([4.28,1.72])
exp_b = np.array([3.57, 1.43])
exp_c = np.array([6.43,2.57])
exp_d = np.array([5.71,2.29])
exp_f = np.array([5,2])

In [35]:
a = (obs_a - exp_a)**2/exp_a
b = (obs_b - exp_b)**2/exp_b
c = (obs_c - exp_c)**2/exp_c
d = (obs_d - exp_d)**2/exp_d
f = (obs_f - exp_f)**2/exp_f
np.sum(a)+np.sum(b)+np.sum(c)+np.sum(d)+np.sum(f)

4.851546688197964

In [43]:
# python library
chi_sq_Stat, p_value, deg_freedom, exp_freq = stats.chi2_contingency(chi_array, correction=False)

print('Chi-square statistic %3.5f P value %1.6f Degrees of freedom %d' %(chi_sq_Stat, p_value,deg_freedom))

Chi-square statistic 4.84361 P value 0.303724 Degrees of freedom 4


**Decision**

As chi_square_stat < chi_c in right tail test, the sample falls in acceptance zone. Hence we cannot reject null hypothesis

Also as p_value < alpha in right tail test, the sample falls in acceptance zone. Hence we cannot reject null hypothesis

students is not impacted by the mode of engagement.

[Q5] The university conducted a course in three centeres and assigned the same question paper. The VC  wants to compare performance of the three batches. Refer to sheet q5 to answer this query.

In [70]:
data5 = pd.read_excel('midterm_data.xlsx', sheet_name = 'q5')                 
data5.head()

batch  rollnum  marks
0      1        1     84
1      1        2     69
2      1        3     74
3      1        4     89
4      1        5     92

In [71]:
data5.tail()

batch  rollnum  marks
88      3       26     84
89      3       27     76
90      3       28     55
91      3       29     61
92      3       30     67

In [ ]:
Here we have 3 batches and we want to compare thier means 
we will be using annova to compare their means

#Null hypo -        
h0: average marks of all these are equal
#Alternamte hypo -  .
h1:average marks of all abtches are not equal(any one can also be different from other)
    
using f test which is right tail test

In [72]:
batch1_marks=np.array(data5.marks[data5.batch==1])
batch2_marks=np.array(data5.marks[data5.batch==2])
batch3_marks=np.array(data5.marks[data5.batch==3])

In [73]:
batch1_marks

array([84, 69, 74, 89, 92, 71, 89, 94, 66, 63, 63, 79, 64, 55, 75, 64, 57,
       67, 68, 58, 60, 56, 54, 90, 61, 82, 80, 69, 81, 86, 59],
      dtype=int64)

In [74]:
batch2_marks

array([59, 91, 83, 51, 83, 69, 80, 55, 87, 68, 85, 91, 93, 73, 55, 79, 93,
       70, 51, 76, 76, 73, 81, 83, 65, 84, 64, 79, 70, 51, 78, 91],
      dtype=int64)

In [75]:
batch3_marks

array([80, 87, 91, 70, 75, 68, 78, 61, 78, 62, 93, 75, 79, 88, 70, 94, 67,
       62, 79, 50, 75, 73, 74, 78, 91, 84, 76, 55, 61, 67], dtype=int64)

In [77]:
# normality tests
stats.shapiro(batch1_marks) #P-value is slightly greater than 0.05 so null is accepted - its a normal distribution

ShapiroResult(statistic=0.9348101615905762, pvalue=0.05935411900281906)

In [78]:
stats.shapiro(batch2_marks)

ShapiroResult(statistic=0.9366849064826965, pvalue=0.06031687557697296)

In [79]:
stats.shapiro(batch3_marks)

ShapiroResult(statistic=0.9750015139579773, pvalue=0.6827733516693115)

In [81]:
#import scipy
stats.levene(batch1_marks,batch2_marks,batch3_marks) #Null accepted, they have same variance 

LeveneResult(statistic=0.5645287972235011, pvalue=0.57062837923048)

In [82]:
f_test, p_val = stats.f_oneway(batch1_marks, batch2_marks, batch3_marks)

In [83]:
f_test

0.6534623826271031

In [84]:
p_val

0.5226918265862517

as p_value>alpha we cannot reject our h0 that is average marks of all these are equal
therefore average marks of all the batches are similar. there is no impact of centre on the marks scored.