**Instructions:**

duration: 2 hours

marks: 30

There are five questions below. Each require a portion answered using python in this notebook and a written answer using pen paper.

Use comments to make your code readable and interpret the results formally. This is NOT a python or ML exam.

Written answers: Briefly answer the following, if applicable, for each question
- Justify the selected test
- State any assumptions for the test
- State and justify the choice of the rejection zone
- State the decision, interpret

In [ ]:
# code snippets that may be useful

# !pip install xlrd
# df = pd.read_excel('sample.xlsx', sheet_name='sheet2')

# stats.norm.cdf(zscore)
# stats.t.cdf(tscore, df=df)

# stats.norm.ppf(probability)
# stats.t.ppf(probability, df=df)

# chi_square_stat, p_value = stats.chisquare(observed_values, f_exp=expected_values)

# chi_sq_Stat, p_value, deg_freedom, exp_freq = stats.chi2_contingency(quality_array, correction=False)


# f_test, p_val = stats.f_oneway(sectionA, sectionB, sectionC)

#mod = ols('marks ~ section', data = marks_df).fit()
#aov_table = sm.stats.anova_lm(mod, typ=2)
#print(aov_table)

In [1]:
# import libraries
import numpy as np
import pandas as pd
from scipy import stats

# ANOVA
import statsmodels.api         as     sm
from   statsmodels.formula.api import ols

In [2]:
import os
os.chdir(r'C:\Users\tejas\Downloads')

[Q1] A cable internet service provider ran two campaigns. In one they offered one month free if the subscriber paid for 6 months. In another they offered two months free if the subscriber paid for 12 months. Data relating to both campaigns are in the data workbook sheets q1 and q11.
Using formal methods, test if they were both equally effective in winning customers.

In [5]:
q1 = pd.read_excel('midterm_data.xlsx', sheet_name='q1')
q1.isnull().sum()

agent_id    0
region      0
pitch       0
result      0
dtype: int64

In [7]:
q11 = pd.read_excel('midterm_data.xlsx', sheet_name='q11')
q11.isnull().sum()

agent_id    0
region      0
pitch       0
result      0
dtype: int64

In [6]:
q1.head()

agent_id region                               pitch         result
0      1429      N  pay for 6 months, get 1 month free              N
1      1047      N  pay for 6 months, get 1 month free              N
2      1356      W  pay for 6 months, get 1 month free  AcceptedOffer
3      1230      W  pay for 6 months, get 1 month free              N
4      1818      E  pay for 6 months, get 1 month free              N

In [14]:
q1.shape

(61, 4)

In [8]:
q11.head()

agent_id region                                 pitch result
0      1013      S  pay for 12 months, get 2 months free      N
1      1042      E  pay for 12 months, get 2 months free      N
2      1044      E  pay for 12 months, get 2 months free      N
3      1052      N  pay for 12 months, get 2 months free      N
4      1074      N  pay for 12 months, get 2 months free      N

In [15]:
q11.shape

(56, 4)

In [ ]:
#subscribers accepting offer in campaign 1

In [11]:
count1_acc= 0
count1_nacc= 0

for i in q1.result:
    if i== 'AcceptedOffer':
        count1_acc= count1_acc+1
        
    elif i== 'N':
        count1_nacc= count1_nacc+1

In [12]:
count1_acc, count1_nacc

(19, 42)

In [ ]:
#subscribers accepting offer in campaign 2

In [16]:
count2_acc= 0
count2_nacc= 0

for i in q11.result:
    if i== 'AcceptedOffer':
        count2_acc= count2_acc+1
        
    elif i== 'N':
        count2_nacc= count2_nacc+1

In [17]:
count2_acc, count2_nacc

(12, 44)

In [107]:
# Chi Square Independence test- Contingency Test. 
#Hypothesis Formulation : Ho : Response to Campaigns 1 and 2 is equal in obs and expected 
        # Ha :Response to Campaigns 1 and 2 not equal in obs and expected 
    
import numpy       as np
import scipy.stats as stats

chi_array = np.array([[19,12],[42,44]])

chi_array

array([[19, 12],
       [42, 44]])

In [20]:
acc= np.sum(chi_array[0])
not_acc= np.sum(chi_array[1])

In [23]:
camp1= chi_array[0][0]+ chi_array[1][0]
camp2= chi_array[0][1]+ chi_array[1][1]

In [24]:
c1_acc= camp1*(acc/(acc+not_acc))
c1_not_acc= camp1*(not_acc/(acc+not_acc))

c2_acc= camp2*(acc/(acc+not_acc))
c2_not_acc= camp2*(not_acc/(acc+not_acc))

In [26]:
chi_exp_array = np.array([[c1_acc,c2_acc],[c1_not_acc,c2_not_acc]])
chi_exp_array 

array([[16.16239316, 14.83760684],
       [44.83760684, 41.16239316]])

In [27]:
chi_c = stats.chi2.isf(0.05,(2-1)*(2-1)) #Chi Square Right tail test.
chi_c



3.8414588206941285

In [28]:
chi_stats = (chi_array - chi_exp_array)**2/chi_exp_array
chi_sq = np.sum(chi_stats)
chi_sq

1.4160677171634835

In [30]:
p_value= stats.chi2.sf(chi_sq,(2-1)*(2-1)) #area right of chi square 

In [32]:
alpha= 0.05
chi_sq, chi_c, p_value, alpha

(1.4160677171634835, 3.8414588206941285, 0.23405172341301897, 0.05)

In [ ]:
#cross-check with inbuilt python function:

In [109]:
import pandas      as pd
import numpy       as np
import scipy.stats as stats

chi_sq_Stat, p_value, deg_freedom, exp_freq = stats.chi2_contingency(chi_array, correction=False)
stats.chi2_contingency(chi_array)

print('Chi-square statistic %3.5f P value %1.6f Degrees of freedom %d' %(chi_sq_Stat, p_value,deg_freedom))
df = (2-1)*(2-1)
print("critical value is ", stats.chi2.isf(0.05, df))

Chi-square statistic 1.41607 P value 0.234052 Degrees of freedom 1
critical value is  3.8414588206941285


### Decision

Based on the method (from scratch) and python library: 
1. Chi Stat  is less than Chi critical for the given right tail test.
2. P_value is greater then alpha.  
As we can see, in right tail Chi test test sample falls in acceptance zone. So we cannot reject Null Hypothesis based on given sample data.
3. Hence, both campaigns were both equally effective in winning customers


[Q2] The agents of the cable internet company are required to make phone calls to customers and offer them deals and win subscriptions. A metric in this process is the number of calls made per day. Initially the agents were paid fixed salary without any incentives for winning new customers. The management recently changed this and offered incentives to the agents hoping they will make more calls per day. This information is available in sheet q2. The columns are Calls_Salary and Calls_Incentive for each agent.

You are required to test if the change in payment to include incentives for winning customers has increased the number of calls made per day.

In [34]:
#Let mu_1 be the average number of calls per day initially.
#mu_2 be the average calls per day after incentives

# H0 : mu_1 - mu_2 >= 0
# H1 : mu_1 - mu_2 < 0   # incentives for winning customers has increased the average number of calls

q2 = pd.read_excel('midterm_data.xlsx', sheet_name='q2')
q2.isnull().sum()
alpha = 0.05                      



In [36]:
q2.shape

(59, 3)

In [37]:
q2.isnull().sum()

agent_id           0
Calls_Salary       0
Calls_Incentive    0
dtype: int64

In [38]:
x1 = np.array(q2["Calls_Salary"])  #Calls before incentives
x2 = np.array(q2["Calls_Incentive"])   #Calls after incentives  
D = x1 - x2
D

array([-3, -3, -3,  3, -7, -1, -7, -4,  1, -3, -3, -5, -4, -4, -3, -4, -3,
       -7, -5, -6, -7, -4,  0,  0, -4, -4, -2, -6, -6, -5,  1, -6,  2, -6,
       -1, -3, -4, -2, -5, -2, -5, -7,  2, -5, -3, -7, -1, -6, -6, -4, -7,
       -6, -3, -3,  0, -3, -6, -8,  2], dtype=int64)

In [44]:
n = len(D)

In [45]:
D_bar = np.mean(D)
S_D = np.std(D,ddof=1)

In [49]:
t_crit = stats.t.ppf(0.05,df=n-1)  #left tailed test
t_crit

-1.6715527621536728

In [50]:
t = (D_bar - 0)/(S_D/np.sqrt(n))
t

-10.252069705503347

In [52]:
pval = stats.t.cdf(t,df=n-1)
pval

6.119313351322935e-15

## Decision
* As t < tc in left tail test, the samples lie in rejection zone. Hence we reject the null hypothesis.
* as p_value < alpha in left tail test, the samples lie in rejection zone. Hence we reject the null hypothesis.
* Hence the impact of incentives is statistically significant for winning customers and has increased the average number of calls

[Q3] University requires grades to be distributed according to their norms:
A (5%), B(30%), C(50%), D(10%), F(5%) 
For a recent exam, the grades were as given in sheet q3.

Test if this follows the norms.

In [77]:
q3 = pd.read_excel('midterm_data.xlsx', sheet_name='q3')
q3.isnull().sum()

rollnumber    0
mode          0
grade         0
dtype: int64

In [78]:
countA= 0
countB= 0
countC= 0
countD= 0
countF= 0

for i in q3.grade:
    if i== 'A':
        countA= countA+1
        
    elif i== 'B':
        countB= countB+1
        
    elif i== 'C':
        countC= countC+1
        
    elif i== 'D':
        countD= countD+1
        
    elif i== 'F':
        countF= countF+1

In [79]:
countA

6

## Chi square goodness of fit test


H0: Observed grade distribution is similar to Expected grade distribution.

H1: Observed grade distribution is not similar to Expected grade distribution.

In [55]:
obs = np.array([countA, countB, countC, countD, countF ])
n= np.sum(obs)
n

35

In [56]:
exp = np.array([n*0.05,n*0.30,n*0.50,n*0.10, n*0.05])

In [58]:
chi_c = stats.chi2.isf(0.05,5-1)
chi_c

9.487729036781158

In [62]:
chi_stats = (obs - exp)**2/exp
chi_sq = np.sum(chi_stats)
chi_sq

38.86666666666667

In [63]:
stats.chi2.sf(chi_sq,5-1)

7.422492853897377e-08

In [61]:
#cross- check with inbuilt library
chi2_c = stats.chi2.isf(0.05, len(obs)-1)
chi2, p_value = stats.chisquare(obs,exp)
chi2, chi2_c, p_value, alpha


(38.86666666666667, 9.487729036781158, 7.422492853897377e-08, 0.05)

## Decision:

Based on the Chi method (from scratch) and python library:   
* As chi_sq > chi2_c in right tail test, the samples lie in rejection zone. Hence we reject the null hypothesis.
* As p_value < alpha in right tail test, the samples lie in rejection zone. Hence we reject the null hypothesis.
* This sample fails to meet the norms.

[Q4] There are keen discussions about online vs classroom in various segments of the society. Using the data in sheet q3, test if performance of students is impacted by the mode of engagement.

In [4]:
#for Classroom segment:


q3 = pd.read_excel('midterm_data.xlsx', sheet_name='q3')
q3.isnull().sum()

q3.grade[q3.option == 'Classroom']




0     D
1     F
2     C
3     C
4     A
7     A
8     A
9     D
11    C
12    A
13    F
14    F
18    B
19    B
22    F
24    D
25    F
26    D
27    C
28    D
29    A
30    C
31    F
32    B
34    A
Name: grade, dtype: object

In [15]:
q3.grade

0     D
1     F
2     C
3     C
4     A
5     C
6     F
7     A
8     A
9     D
10    D
11    C
12    A
13    F
14    F
15    C
16    C
17    C
18    B
19    B
20    D
21    D
22    F
23    B
24    D
25    F
26    D
27    C
28    D
29    A
30    C
31    F
32    B
33    B
34    A
Name: grade, dtype: object

In [16]:
q3.mode

<bound method DataFrame.mode of     rollnumber       mode grade
0            1  Classroom     D
1            2  Classroom     F
2            3  Classroom     C
3            4  Classroom     C
4            5  Classroom     A
5            6     Online     C
6            7     Online     F
7            8  Classroom     A
8            9  Classroom     A
9           10  Classroom     D
10          11     Online     D
11          12  Classroom     C
12          13  Classroom     A
13          14  Classroom     F
14          15  Classroom     F
15          16     Online     C
16          17     Online     C
17          18     Online     C
18          19  Classroom     B
19          20  Classroom     B
20          21     Online     D
21          22     Online     D
22          23  Classroom     F
23          24     Online     B
24          25  Classroom     D
25          26  Classroom     F
26          27  Classroom     D
27          28  Classroom     C
28          29  Classroom     D
29      

In [23]:
#for online segment:

grade_online=[]

if q3.mode== "Online":
    for i in q3.grade:
        grade_online.append(i)
        
grade_online
        

[]

In [22]:
q3.grade

0     D
1     F
2     C
3     C
4     A
5     C
6     F
7     A
8     A
9     D
10    D
11    C
12    A
13    F
14    F
15    C
16    C
17    C
18    B
19    B
20    D
21    D
22    F
23    B
24    D
25    F
26    D
27    C
28    D
29    A
30    C
31    F
32    B
33    B
34    A
Name: grade, dtype: object

In [67]:
chi_array = np.array([[countA_c, countB_c, countC_c, countD_c,countF_c ],[countA_o, countB_o, countC_o, countD_o,countF_o]])

chi_array

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# There is error while importing the data.

[Q5] The university conducted a course in three centeres and assigned the same question paper. The VC  wants to compare performance of the three batches. Refer to sheet q5 to answer this query.

In [11]:
q5 = pd.read_excel('midterm_data.xlsx', sheet_name='q5')
q5.isnull().sum()

batch      0
rollnum    0
marks      0
dtype: int64

In [12]:
# H0 : mu_batch_1 = mu_batch_2 = mu_batch_3
# H1 : not all means are equal

a = q5.marks[q5.batch == 1]
b = q5.marks[q5.batch == 2]
c = q5.marks[q5.batch == 3]

al=np.concatenate((a,b,c),axis=None)

a_ssw=np.sum((a-a.mean())**2)
b_ssw=np.sum((b-b.mean())**2)
c_ssw=np.sum((c-c.mean())**2)
SSW=(a_ssw+b_ssw+c_ssw)
SSW

13377.567137096774

In [13]:
q5.marks[q5.batch == 1]

0     84
1     69
2     74
3     89
4     92
5     71
6     89
7     94
8     66
9     63
10    63
11    79
12    64
13    55
14    75
15    64
16    57
17    67
18    68
19    58
20    60
21    56
22    54
23    90
24    61
25    82
26    80
27    69
28    81
29    86
30    59
Name: marks, dtype: int64

In [103]:
al.shape

(93,)

In [102]:
a_ssb=np.sum(len(a)*(a.mean()-al.mean())**2)



b_ssb=np.sum(len(b)*(b.mean()-al.mean())**2)


c_ssb=np.sum(len(c)*(c.mean()-al.mean())**2)


SSB=a_ssb+b_ssb+c_ssb
SSB

194.26081989247362

In [110]:
#c= 3 (c is no of categories)
# mean sq between
MSB=SSB/(3-1)
MSB

#n is no. of observation
#c= 3 (c is no of categories)
# Mean sq within the groups
MSW=SSW/(93-3)
MSW


f_stat=MSB/MSW
f_stat

from scipy import stats
f_critic = stats.f.isf(0.05,dfn=3-1,dfd=93-3)
f_critic,f_stat

# P_value 
P_Value = stats.f.sf(f_stat,dfn=3-1,dfd=93-3)


f_critic,f_stat,P_Value




(3.097698035251924, 0.6534623826271045, 0.5226918265862517)

In [105]:
# cross-check with inbuilt library of one way ANOVA
f_test, p_val = stats.f_oneway(a, b, c)
print(f_test)
print(p_val)

0.6534623826271031
0.5226918265862517


## Decision  

Based on the ANOVA method (from scratch) and python library:

-- Here the p_value >0.05 for factors hence we fail to reject null hypothesis. Hence, there is no impact of centre on the marks scored.